#version 410 core

// cloth.vert — Cloth mesh vertex shader (OpenGL 4.1 core profile)
//
// Particle positions are read from a Texture Buffer Object (TBO) via gl_VertexID.
// SSBOs require OpenGL 4.3 (unavailable on macOS); TBOs are available since 3.1.
//
// TBO layout (GL_RGBA32F, matches Particle struct in sim/cloth.h):
//   texel i*2   = particle[i].pos   (xyz = world pos, w = mass_inv)
//   texel i*2+1 = particle[i].vel   (xyz = velocity,  w = flags)
//
// The index buffer (generated by ClothMesh::init) already encodes the grid topology,
// so each draw call vertex maps to exactly one particle via gl_VertexID.

uniform mat4         uMVP;     // projection * view * model  (model = identity for cloth)
uniform samplerBuffer uPosTBO; // particle buffer as flat float4 texels

void main()
{
    // Read position from TBO — texel i*2 holds pos (xyz = world position)
    vec3 pos = texelFetch(uPosTBO, gl_VertexID * 2).xyz;
    gl_Position = uMVP * vec4(pos, 1.0);
}
